### PR TITLE
Mongoose

### PR DESCRIPTION
**Pull request by iahelr**

### CODE REVIEW

**Comment by limonana** [comment]
why you insert the InitDB into the server? it is a different app.

**Comment by limonana** [comment]
getMovieById need  to return null if the id is not valid

**Comment by iahelr** [comment]
InitDB  is in the server cause it is a server Feedback
Web results responsibility to fill data even if it just mock
and  getMovieById  return by default null id not found:)

**Comment by limonana** [comment]
"InitDB is in the server cause it is a server Feedback "
didn't understand. it is a different app.
שני פדידה

**Comment by limonana** [comment]
what happing now with the connection? is it shared?

**Pull request merged**
